name: Build WPF App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore KPL-FE/KPL-FE.csproj

      - run: dotnet publish KPL-FE/KPL-FE.csproj -c Release -o publish -r win-x64 --self-contained false

      - uses: actions/upload-artifact@v4
        with:
          name: KPL-FE
          path: publish/
